---
- targets:
  - "node-exporter:9100"
  labels:
    node_id: "1"
    nodename: "central-node"
    job: "node-exporter"
    environment: "central-node"
- targets:
  - "cadvisor:8080"
  labels:
    node_id: "1"
    nodename: "central-node"
    job: "cadvisor"
    environment: "central-node"
- targets:
  - "filebeat:5066"
  labels:
    node_id: "1"
    nodename: "central-node"
    job: "filebeat"
    environment: "central-node"
- targets:
  - "backend:8880"
  labels:
    node_id: "1"
    nodename: "central-node"
    job: "monetique-backend"
    environment: "central-node"
- targets:
  - "frontend:80"
  labels:
    node_id: "1"
    nodename: "central-node"
    job: "monetique-frontend"
    environment: "central-node"


- targets:
  - "192.168.126.133:9100"
  labels:
    node_id: "2"
    nodename: "node-133"
    job: "node-exporter"
    environment: "demo-pre-prod"
- targets:
  - "192.168.126.133:8085"
  labels:
    node_id: "2"
    nodename: "node-133"
    job: "cadvisor"
    environment: "demo-pre-prod"
- targets:
  - "192.168.126.133:5066"
  labels:
    node_id: "2"
    nodename: "node-133"
    job: "filebeat"
    environment: "demo-pre-prod"
- targets:
  - "192.168.126.133:8880"
  labels:
    node_id: "2"
    nodename: "node-133"
    job: "monetique-backend"
    environment: "demo-pre-prod"
- targets:
  - "192.168.126.133:80"
  labels:
    node_id: "2"
    nodename: "node-133"
    job: "monetique-frontend"
    environment: "demo-pre-prod"
