---
- targets:
  - "node-exporter:9100"
  labels:
    node_id: "1"
    nodename: "central-node"
    job: "node-exporter"
    environment: "central-node"
- targets:
  - "cadvisor:8080"
  labels:
    node_id: "1"
    nodename: "central-node"
    job: "cadvisor"
    environment: "central-node"
- targets:
  - "filebeat:5066"
  labels:
    node_id: "1"
    nodename: "central-node"
    job: "filebeat"
    environment: "central-node"
- targets:
  - "backend:8880"
  labels:
    node_id: "1"
    nodename: "central-node"
    job: "monetique-backend"
    environment: "central-node"
- targets:
  - "frontend:80"
  labels:
    node_id: "1"
    nodename: "central-node"
    job: "monetique-frontend"
    environment: "central-node"


