---
- targets:
  - "http://backend:8880/actuator/health"
  labels:
    nodename: "central-node"
    target_type: "node"
    job: "blackbox"
    probe_module: "http_2xx"
    environment: "central-node"
- targets:
  - "http://frontend:80"
  labels:
    nodename: "central-node"
    target_type: "frontend"
    job: "blackbox"
    probe_module: "http_2xx"
    environment: "central-node"

