---
- name: Deploy Backend Application to Agent Node
  hosts: agents
  become: yes
  vars:
    # Defaults that should be overridden by extra-vars from the backend
    appName: "backend"
    image_tag: "v1"
    central_ip: "" # Overridden by backend
    db_name: "monetique-eye-db"
    db_user: "youss"
    db_pass: "youss123"
    jwt_secret: "PhcZW4LAR674QdgudEwzNvRdNkSncHA8Sx4tkF4pY9xT78Ght14z88OVdP9z7GUKiXjKhEyaZHI6aBsjqmAYAYWiVMVej5RSfzpCGQ4mvQ1zYJZBMLinlZv1NT3JDZWcnbRIWyu6UVqmwEp1T1QVZH37JsyJUuYVsA5dylNyjJLFMhZ"

  tasks:
    - name: Remove old backend container if exists
      shell: "docker rm -f {{ appName }} || true"
      changed_when: false

    - name: Run Backend Container
      shell: |
        docker run -d --name {{ appName }} \
        --restart=always \
        --log-driver json-file \
        --label com.monetique.service="{{ appName }}" \
        --label com.monetique.environment={{ env_label | default('production') }} \
        --label node={{ ansible_hostname }} \
        -p 8880:8880 \
        -p 9001:9001 \
        -e SERVER_PORT=8880 \
        -e SPRING_DATASOURCE_URL=jdbc:mysql://{{ central_ip }}:3306/{{ db_name }}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false \
        -e SPRING_DATASOURCE_USERNAME={{ db_user }} \
        -e SPRING_DATASOURCE_PASSWORD={{ db_pass }} \
        -e JWT_SECRET={{ jwt_secret }} \
        -e LOGSTASH_HOST={{ central_ip }} \
        -e LOGSTASH_PORT=5044 \
        -e ELASTICSEARCH_URL=http://{{ central_ip }}:9200 \
        -e PROMETHEUS_URL=http://{{ central_ip }}:9090 \
        -e NODE_NAME="{{ ansible_hostname }}" \
        {{ appName }}:{{ image_tag }}
      args:
        executable: /bin/bash
